#!/bin/sh
#USB version
sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
sleep 20
apt-get update
inc=0
umount -R /mnt/*
sleep 5
rm -R /mnt/*
echo -en "\007"
sleep 5
#for i in $(lsblk -dpno name| awk '!/loop|sr|nvme/'); do
for i in $(lsblk -dpn | awk '/disk/ {print $(NR01)}' | awk '!/cdrom|nvme/ {print $1}'); do
	echo $i
	sleep 1
	wipefs -a $i
	sleep 1
	parted -s $i mklabel msdos
	sleep 1
	parted -s $i mkpart primary ext4 0% 100%
	sleep 1
	inc=$((inc+1))
	sleep 1
	mkfs.ext4 -F $i"1"
	sleep 1
	mkdir /mnt/disk$inc
	sleep 1
	mount $i"1" /mnt/disk$inc
done

incnvme=0

for a in $(lsblk -dpno name| awk '!/loop|sr|sd/'); do
        echo $a
	sleep 1
        wipefs -a $a
	sleep 1
        parted -s $a mklabel msdos
	sleep 1
        parted -s $a mkpart primary ext4 0% 100%
	sleep 1
        incnvme=$((incnvme+1))
	sleep 1
        mkfs.ext4 -F $a"p1"
	sleep 1
        mkdir /mnt/nvme$incnvme
	sleep 1
	mount $a"p1" /mnt/nvme$incnvme
done

wget https://raw.githubusercontent.com/frestok/Test/master/html_results_export_table.php -O /usr/share/phoronix-test-suite/pts-core/modules/html_results_export.php

#wget http://192.168.0.116/Files/html_results_export.php -O /usr/share/phoronix-test-suite/pts-core/modules/html_results_export.php

#export EXPORT_RESULTS_HTML_EMAIL_TO=a.karaliou@asbis.com,a.novik@asbis.com,d.martakov@asbis.com,M.Moshkovsky@asbis.com,D.Teryokhin@prestigio.eu
export EXPORT_RESULTS_HTML_EMAIL_TO=a.karaliou@asbis.com


#phoronix-test-suite batch-benchmark pts/systemd-boot-total

phoronix-test-suite batch-benchmark pts/scimark2

#phoronix-test-suite batch-benchmark server

sleep 10
umount -R /mnt/*
sleep 10

for b in $(lsblk -dpn | awk '/disk/ {print $(NR01)}' | awk '!/cdrom/ {print $1}'); do
	echo $b
	wipefs -a $b
done

sudo poweroff
