#!/bin/sh
apt-get update
inc=0
umount -R /mnt/*
rm -R /mnt/*
for i in $(lsblk -dpno name| awk '!/loop|sr|nvme/'); do
	echo $i
	sleep 1
	wipefs -a $i
	sleep 1
	parted -s $i mklabel msdos
	sleep 1
	parted -s $i mkpart primary ext4 0% 100%
	sleep 1
	inc=$((inc+1))
	sleep 1
	mkfs.ext4 -F $i"1"
	sleep 1
	mkdir /mnt/disk$inc
	sleep 1
	mount $i"1" /mnt/disk$inc
done

incnvme=0

for a in $(lsblk -dpno name| awk '!/loop|sr|sd/'); do
        echo $a
	sleep 1
        wipefs -a $a
	sleep 1
        parted -s $a mklabel msdos
	sleep 1
        parted -s $a mkpart primary ext4 0% 100%
	sleep 1
        incnvme=$((incnvme+1))
	sleep 1
        mkfs.ext4 -F $a"p1"
	sleep 1
        mkdir /mnt/nvme$incnvme
	sleep 1
	mount $a"p1" /mnt/nvme$incnvme
done

wget https://raw.githubusercontent.com/frestok/Test/master/html_results_export_table.php -O /usr/share/phoronix-test-suite/pts-core/modules/html_results_export.php

#wget http://192.168.0.116/Files/html_results_export.php -O /usr/share/phoronix-test-suite/pts-core/modules/html_results_export.php

export EXPORT_RESULTS_HTML_EMAIL_TO=a.karaliou@asbis.com


#phoronix-test-suite batch-benchmark pts/systemd-boot-total

phoronix-test-suite batch-benchmark pts/scimark2

#phoronix-test-suite batch-benchmark server

sleep 10
umount -R /mnt/*
sleep 10

for b in $(lsblk -dpno name| awk '!/loop|sr/'); do
	echo $b
	wipefs -a $b
done

sudo poweroff
